server:
  protocol: http
  host: 192.168.1.105
  port: 8000

rsshub:
  protocol: http
  host: omv.local
  port: 1200

redis:
  protocol: redis
  host: omv.local
  port: 6379

cache:
  task_queue: podcast:queue:download_task
  is_queued: podcast:queue:queued
  expire_seconds: 86400

listen:
  bilibili:
    user:
      - id: 199676483
        author: MHYYYY
        title: MHYYYY
        image_url: https://i2.hdslb.com/bfs/face/f7e24cfec824e0aaf67fdd62c960c13026768f70.jpg
        category:
          - 键政
        description: 键政人
    route: user/dynamic
    video_url_prefix: https://www.bilibili.com/video/

storage:
  root_path: /tmp/podcast
  video: /video
  audio: /audio
  episode: /episode
  static: /static

podcast:
  max_episodes: 10
