rsshub:
  protocol: http
  host: omv.local
  port: 1200
redis:
  protocol: redis
  host: omv.local
  port: 6379
queue:
  task_queue: podcast:queue:download_task
  is_queued: podcast:queue:queued
listen:
  bilibili:
    - 199676483